# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo:2.4.14
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./database/mongo:/data/db
  atlante:
    container_name: atlante
    image: daquinoaldo/atlante
    restart: "no"
    links:
      - mongo
  api:
    container_name: api
    image: daquinoaldo/api
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app