# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo:2.4.14
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./database/mongo:/data/db